modLoader="javafml"
loaderVersion="[4,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="flesh_and_volition"
version="0.0.1"
displayName="Flesh And Volition"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="0pt1mist"
displayTest="IGNORE_SERVER_VERSION"

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.flesh_and_volition]]
    modId="neoforge"
    type="required"
    versionRange="[21.8.31,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.flesh_and_volition]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.8]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.flesh_and_volition]]
    modId="jei"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration